#!/usr/bin/env bash

# Only root allowed to run this script

if [[ $(whoami) != 'root' ]]; then
	echo 'This script must be run by root' >&2
	exit 1
fi

# Stop service

systemctl stop rcon-web > /dev/null 2>&1

# Create rcon-web system user if not exists

id -u rcon-web > /dev/null 2>&1 || adduser --system --group --no-create-home --shell /bin/false rcon-web

# Copy syslog & service configuration

cp -f system/etc/rsyslog.d/40-rcon-web.conf /etc/rsyslog.d/
cp -f system/lib/systemd/system/rcon-web.service /lib/systemd/system/

# Copy files to server directoty

mkdir -p /srv/rcon-web

cp -n .rconrc  /srv/rcon-web/
cp rcon-web /srv/rcon-web/

rm -rf /srv/rcon-web/static
rm -rf /srv/rcon-web/templates

cp -r static /srv/rcon-web/
cp -r templates /srv/rcon-web/

chown rcon-web:rcon-web -R /srv/rcon-web
chmod 440 -R /srv/rcon-web
chmod 550 -R /srv/rcon-web/rcon-web
find /srv/rcon-web -type d | xargs chmod 550

# Restart rsyslog service

service rsyslog restart

# Enable & start service

systemctl daemon-reload
systemctl enable rcon-web
systemctl start  rcon-web
